artifact_uri: /d01/training_data/yolo-other/yolo26-seg-depth/runs/mlflow/174190924573537043/bf2c040eb8d448eaafd301fe8f093bfd/artifacts
end_time: null
entry_point_name: ''
experiment_id: '174190924573537043'
lifecycle_stage: active
run_id: bf2c040eb8d448eaafd301fe8f093bfd
run_name: exp_coco80_depth
run_uuid: bf2c040eb8d448eaafd301fe8f093bfd
source_name: ''
source_type: 4
source_version: ''
start_time: 1777365854269
status: 1
tags: []
user_id: xtladmin
