artifact_uri: /d01/training_data/yolo-other/yolo26-seg-depth/runs/mlflow/174190924573537043/4a7c132a5ecf4ad8a0d9705ba7cefdc8/artifacts
end_time: 1777361582390
entry_point_name: ''
experiment_id: '174190924573537043'
lifecycle_stage: active
run_id: 4a7c132a5ecf4ad8a0d9705ba7cefdc8
run_name: exp_nyu_fixed3
run_uuid: 4a7c132a5ecf4ad8a0d9705ba7cefdc8
source_name: ''
source_type: 4
source_version: ''
start_time: 1777361102429
status: 3
tags: []
user_id: xtladmin
